-- Generated by scripts/hypr2lua.
-- Source: omarchy-01-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(ab92fc)", "rgb(875faf)" },
  angle = 90,
}
local inactiveBorderColor = {
  colors = { "rgba(e6bb85aa)", "rgba(d99145bb)" },
  angle = 90,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 8,
    gaps_out = 16,
    border_size = 3,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("silk_drop", { type = "bezier", points = { { 0.42, 1.60 }, { 0.80, 1 } } })

hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 3.5,
  bezier = "silk_drop",
  style = "slidevert",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 2.5,
  bezier = "silk_drop",
})
